name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.3'
    - name: Set up Docker
      run: docker network create test
    - name: Set up Postgres
      run: docker run -d --name pg --network test -e POSTGRES_USER=bouncer -p 5432:5432 postgres:11
    - name: Build a new Docker image
      run: docker build . --build-arg RAILS_ENV=test -t bouncer:test
    - name: Set up a new container for testing
      run: |
        docker run -d --name test-container \
          --network test \
          -e RAILS_ENV=test \
          -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true \
          -e DATABASE_URL=postgres://bouncer@pg:5432/bouncer \
          bouncer:test /bin/bash -c "tail -f /dev/null"
    - name: Set up the test database
      run: |
        docker run --network test -v $(pwd):/bouncer -e POSTGRES_USER=bouncer postgres:11 \
        /bin/bash -c "cat bouncer/db/structure.sql | psql 'postgresql://bouncer@pg:5432/bouncer'"
    - name: Run the tests
      run: docker exec test-container rake
